export const CartActionTypes = {
  TOGGLE_CART_COMPONENT: 'TOGGLE_CART_COMPONENT',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  GET_CART_LENGTH: 'GET_CART_LENGTH',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',

}